# Generated by Django 5.2.5 on 2025-09-04 20:24

import users.models.profile_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_follows_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.profile_model.user_profile_picture_path),
        ),
    ]
