version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=xdevuser
      - POSTGRES_PASSWORD=xdevpassword
      - POSTGRES_DB=xdevdb
    ports:
      - "5432:5432" 


  web:
    build: .
    container_name: django_web
    command: gunicorn xdev.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
  media_volume: